### ISSUE TITLE
sFTP folders

### ISSUE THREAD

**Issue by sierracircle** [antoniocoratelli/bookmarks-indicator#1] opened 2016-09-15 17:18 UTC
If bookmarks-indicator could list/open sFTP folders, it would be an invaluable tool for me.
If bookmarks-indicator could have a way to GROUP sFTP folders, I would use it every day...perhaps with a quickname for the bookmark

Something like:
# WebProjects

   owncloud [sftp://admin@mydomain.com:21212/home/admin]
   website [sftp://website@mydomain.com:21212/home/website]
   office [sftp://office@mydomain.com:21212/home/office]

 #DatabaseApplications
   mas [sftp://mas@mas.com:21212/home/other]
   personal [sftp://personal@thisdomain.com:21212/home/me]
   otherthing [sftp://otherthing@mydomain.com:21212/home/mas]

I have been looking for a way to move my sftp folders off of the Nautilus Bookmarks...I just have too many sFTP folders and it makes Nautilus Bookmarks unusable.
If I had a way to have a short-cut name and group my sFTP folders to open quickly, it would be an incredibly useful tool!!

**Comment by antoniocoratelli** [comment] 2016-09-15 18:07
have you tried to mount your sftp locations to some folders?
I found this guide googling: http://blog.damontimm.com/how-to-mount-a-sftp-folder-ssh-ftp-on-ubuntu-linux-using-sshfs-fuse/
if you can mount them, then you can add the mount path to the bookmarks-indicator config. let me know :)

with regard to the grouping, at the moment you can use the triple dash `---` in config file, I'll try to see if I can add something like a separator with a title

**Comment by sierracircle** [comment] 2016-09-15 18:23
I have in the past successfully done that with fuse, but there are some issues that come with that, and also managing is not very easy when you have many sftp folders  (currently my Nautilus bookmarks have over 50 sftp folders).
I am a web and database developer, and have been wishing for a better way to handle my sftp folders.

 Your indicator seems hopeful, but I do not know enough about how it functions.

  I tried to add an sftp folder but it would not pass the error checking (says "not a folder")

**Comment by antoniocoratelli** [comment] 2016-09-15 18:38
I just pushed in 9e0330b03f6869bcea033d07986be5298b6d03c9 the changes that add support for separators with titles (thanks for the suggestion).

I'll try to work on the sftp support i the next days :)

**Comment by antoniocoratelli** [comment] 2016-09-15 18:38
reminder for myself: https://pypi.python.org/pypi/pysftp

**Comment by sierracircle** [comment] 2016-09-15 18:39
You should add a "donate" link somewhere..

**Comment by antoniocoratelli** [comment] 2016-09-15 20:17
ok, I create a beta version for sftp support (it works only if you login with ssh keys, not using password)

if you'd like to try it clone my repo, `git checkout feature--sftp`, `sudo apt-get install sshfs` and place an entry in the config file like this:

```
sftp|Item Name|username@domain:/home
```

PS: I added a donate link :)

**Comment by sierracircle** [comment] 2016-09-15 20:57
I use ssh keys, and an alternative port (not 22)    where would I add that?

sftp|Item Name|username@domain:/home

Using sshfs like this works:
sshfs -o PORT=3222  user@domain.com:/home/user   /home/user/folder

**Comment by antoniocoratelli** [comment] 2016-09-15 21:07
```
sftp|Item Name|username@domain:/home|21212
```

pull changes again from the repo, I just enabled alternative ssh port

**Comment by sierracircle** [comment] 2016-09-15 21:34
It is acting like it wants to work, but it just freezes nautilus and then gives me a disconnect error.

..just a thought, but is it necessary to use sshfs? I can just launch Nautilus like this:
nautilus sftp://user@mydomain.com:3222/home/user

**Comment by antoniocoratelli** [comment] 2016-09-15 22:00
oh... I thought you needed to navigate through folders using the indicator

in that case do a `git checkout master` and:
- create a file anywhere you want, say `/home/user/my-sftp/owncloud.desktop` with this content:

```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Exec=nautilus sftp://user@mydomain.com:3222/home/user
Name=owncloud
```
- `chmod +x /home/user/my-sftp/owncloud.desktop`
- add `/home/user/my-sftp/owncloud.desktop` to bookmarks-indicator config file

**Comment by sierracircle** [comment] 2016-09-15 22:14
Navigating through the folder(s) is not necessary...just a launcher would work for my purposes
I tried your method, but it simply opens the desktop file in my text-editor..

**Comment by antoniocoratelli** [comment] 2016-09-15 22:28
mmm... ensure it is executable, and try to remove the first line of the file "#!/..."
if it doesn't work I'll see tomorrow what else I can do

**Comment by sierracircle** [comment] 2016-09-15 22:33
Yes, it is executable. I can click on the file and it launches the sftp folder in nautilus.
 I removed the first line and had the same result.

**Comment by antoniocoratelli** [comment] 2016-09-16 08:59
try this one:
- pull changes from my repo and `git checkout feature--execute-script`
- create a file named like `owncloud.sftp` with the following content

```
#!/bin/bash
nautilus sftp://user@mydomain.com:3222/home/user
```
- `chmod +x owncloud.sftp`
- add `owncloud.sftp` path to bookmarks-indicator config file (or add its parent folder)
- launch `bookmarks-indicator.py` with argument `-x '.sftp'`

(you can use any extension you like)

**Comment by sierracircle** [comment] 2016-09-16 13:37
I followed the instructions exactly, but am getting the same results (opens in text editor rather than launching the command)
I also tried changing the preferences in nautilus to "run executable text files when they are open" but it did not make a difference.

Is it working for you? What version of Ubuntu are you using?

**Comment by antoniocoratelli** [comment] 2016-09-16 13:43
Yes it works for me, I use 14.04
it seems really strange... if you launch `owncloud.sftp` in your shell using `./owncloud.sftp` -- no `bash` or `sh` prefix -- what happens?

**Comment by antoniocoratelli** [comment] 2016-09-16 13:51
in `bookmarks-indicator.py` change at line 173

```
        if extension in self.executables:
            p = subprocess.Popen([path])
        else:
            p = subprocess.Popen([self.opener, path])
```

to:

```
        if extension in self.executables:
            print "recognized", extension, self.executables
            p = subprocess.Popen([path])
        else:
            print "normal file", extension, self.executables
            p = subprocess.Popen([self.opener, path])
```

please tell me the output when you click on `owncloud.sftp` in the indicator

**Comment by sierracircle** [comment] 2016-09-16 14:26
I am using 16.04, if that makes any difference.

If launch the file in a shell, it opens nautilus at the sftp folder (as expected)
If I double-click on the file, it also opens nautilis at the sftp folder

When I changed the lines you just gave me, and then launch it from the indicator, it gives me this:
`normal file  ['.sftp']`
and then opens the file with my text-editor

**Comment by antoniocoratelli** [comment] 2016-09-16 14:35
perfect, so the problem is in `_, extension = os.path.splitext(path)` which weirdly has a different behaviour in 14.04 and 16.04 :confused: 

change:

```
        _, extension = os.path.splitext(path)
        if extension in self.executables:
```

to:

```
        if path.endswith(tuple(self.executables)):
```

**Comment by sierracircle** [comment] 2016-09-16 15:08
Sorry for the delay.

Should the change you just said be made on top of the previous changes? Or should I revert back to where it was (after git checkout feature--execute-script)

**Comment by antoniocoratelli** [comment] 2016-09-16 15:09
make changes on top, just delete `, extension` from the two `print` lines

**Comment by sierracircle** [comment] 2016-09-16 15:13
Ok..I have the following:

```
        When the user clicks on a file, open it in the default program.
        '''
        if path.endswith(tuple(self.executables)):
            p = subprocess.Popen([path])
        else:
            p = subprocess.Popen([self.opener, path])
```

However, it is giving me the same result (opening in text file)

**Comment by antoniocoratelli** [comment] 2016-09-16 15:20
change:

```
    def onclick(self, widget, path):
        '''
        When the user clicks on a file, open it in the default program.
        '''
        if path.endswith(tuple(self.executables)):
            p = subprocess.Popen([path])
        else:
            p = subprocess.Popen([self.opener, path])
```

to:

```
    def onclick(self, widget, path):
        '''
        When the user clicks on a file, open it in the default program.
        '''
        if path.endswith(tuple(self.executables)):
            print "recognized '%s' -- %s" % (path, self.executables)
            p = subprocess.Popen([path])
        else:
            print "normal file '%s' -- %s" % (path, self.executables)
            p = subprocess.Popen([self.opener, path])
```

plese paste the output and your config file

**Comment by sierracircle** [comment] 2016-09-16 15:20
If it is at all helpful:

If I change it to this it works:

```
        if path.endswith(tuple(self.executables)):
            p = subprocess.Popen([path], shell=True)
        else:
            p = subprocess.Popen([path], shell=True)
```

so I am guessing it is just not identifying the file as a shell script?

**Comment by antoniocoratelli** [comment] 2016-09-16 15:21
if you use that code it will try to execute your normal files, which can have some unexpected effect, be careful
for some reason the detection fails, maybe you have some extra whitespace in your config file?

**Comment by sierracircle** [comment] 2016-09-16 15:24
First: Here is the output after making the last requested changes:
`normal file '/home/me/bookmarks-indicator/sftp/s1web' -- []`

Second: no whitespaces in config file, as the indicator fails to launch if there are whitespaces

**Comment by antoniocoratelli** [comment] 2016-09-16 15:25
you have to call `bookmarks-indicator.py` with `-x '.sftp'` and `/home/me/bookmarks-indicator/sftp/s1web` must have `.sftp` extension too!

**Comment by sierracircle** [comment] 2016-09-16 15:27
Okay. I must have missed a step. If I give the launcher-script the extenstion .sftp and launch the indicator with    -x '.sftp'  then it works

**Comment by antoniocoratelli** [comment] 2016-09-16 15:30
yup! eventually you can use `-x '._'` and call the file `/home/me/bookmarks-indicator/sftp/s1web._` or even `-x '.sh'` for `/home/me/bookmarks-indicator/sftp/s1web.sh`

this will execute **all** `*._` or **all** `*.sh` files you click on through the indicator, so be careful :)

I'll leave the issue open for some days, please continue using this branch of the program for some time, if you have no further problems than I'll merge in `master` and close the issue

**Comment by sierracircle** [comment] 2016-09-16 15:33
I back-tracked and find that it works from when you had me do this change:

change:

```

        _, extension = os.path.splitext(path)
        if extension in self.executables:
```

to:

`if path.endswith(tuple(self.executables)):`

..and launch the indicator with -x '.sftp'
..and give the script the extension .sftp

**Comment by antoniocoratelli** [comment] 2016-09-16 15:34
ok perfect, I'll commit that changes and push to `feature--execute-script`

**Comment by sierracircle** [comment] 2016-09-16 15:35
Thanks for all of the extra effort!
This indicator will be very useful to me now. If I have time this weekend I will try to come up with a script to auto-generate the .sftp files

**Comment by antoniocoratelli** [comment] 2016-09-16 15:37
you're welcome :D 
just let me know in a week if you have no other issues with the branch so I can merge ;)

**Comment by sierracircle** [comment] 2016-09-17 18:44
If you are using this method to add your sFTP folders, and want to quickly import your sFTP bookmarks from nautilus, I have created this script that will do that. Note that it just looks for sFTP bookmarks, but it could easily be modified to import all bookmarks.

put this script in your _bookmarks-indicator_ directory and run it:

```

#!/bin/bash

#this will look at your nautilus sFTP bookmarks
#and add them to the bookmarks-indicator

#find the working directory where this script is
DIR=( `dirname "$(readlink -f "$0")"` )
#cd into the working directory
cd  $DIR

       #check if sftp directory exists. if not create it
       if [ ! -d "sftp" ]; then
       mkdir -p sftp ;
       fi

#read through the bookmarks and create an sftp file for each sFTP bookmark
cat ~/.config/gtk-3.0/bookmarks | while read f1 f2
do
#check if config is an sftp bookmark
if [[ $f1 == *"sftp://"* ]]
 then
    #check if that file exists so we dont overwrite existing bookmarks
    if [ ! -f "sftp/$f2.sftp" ]; then
        #if not create it and add the commands and sftp path
        touch "sftp/$f2.sftp"
        echo  "#!/bin/bash" >>  "sftp/$f2.sftp"
        echo  "nautilus $f1" >>  "sftp/$f2.sftp"
        #make it executable
        chmod +x "sftp/$f2.sftp"
    fi
fi
done


#check if config has ---sFTP section
if grep -Fq "sFTP" config
     then 
      :
      else 
      #if not add it to config
      echo "---sFTP" >> config
fi

#finally check if bookmarks exist in config and add them if they do not
for entry in "sftp"/*
do
    if grep -Fq $DIR/"$entry" config
     then 
       :
       else
       #add to config
       echo $DIR/"$entry" >> config
    fi
done

```

**Comment by antoniocoratelli** [comment] 2016-09-18 08:42
Thanks for sharing the code!
If you'd like to add it to the repo send me a pull request, placing the script it in a folder called `extras`. I think that just the `DIR=( `dirname "$(readlink -f "$0")"` )` line should be changed

**Comment by sierracircle** [comment] 2016-09-21 16:39
...I have been using this for the past few days and everything is working great.  I am currently exploring how to open the links in a new tab rather than a new window.
This seems to be complicated, but I am trying the script from this answer:
http://askubuntu.com/questions/628084/what-is-the-command-to-open-a-specific-directory-in-a-new-tab-in-nautilus

**Comment by antoniocoratelli** [comment] 2016-09-21 18:23
perfect, I'll merge `feature--execute-script` in `master` and close this issue.

if you want to open folders in a nautilus new tab, you can create a new Python or Bash script, called for example `my-opener`, and run `python bookmarks-indicator.py -o my-opener`. This requires that `my-opener` script is somewhere in your `$PATH`, otherwise you must specify `my-opener` full path.

`my-opener` should be something that accepts an argument and works like this (pseudo-code):

```
if $argument is a file:
    xdg-open $argument
if $argument is a directory:
    nautilus-new-tab $argument
```

this check is necessary since `bookmarks-indicator.py` uses the `-o` opener option for both files and directories.

**Comment by antoniocoratelli** [comment] 2016-09-21 18:33
merged!
if you succeed and want to share the code for `nautilus-new-tab` feel free to open a new PR (always placing the script in `extras` folder)

anyway  if I have some spare time I'll try to work on it on my own, since it seems a useful feature :)

**Closed as completed by antoniocoratelli** 2016-09-21 18:33 UTC
Labels: enhancement
